[package]
name = "prime-rust-stack"
version = "0.1.0"
authors = ["vavanade"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typenum = "1.13.0"
bit-array = "0.4.4"
